name: Run curl and save webpage every 2 minutes

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes

jobs:
  save-webpage:
    runs-on: ubuntu-latest  # Replace with your preferred runner

    steps:
      - uses: actions/checkout@v3  # Checkout your repository code

      - name: Run curl command and capture output
        run: |
          curl_output=$(curl "http://worldtimeapi.org/api/timezone/Europe/London")
          echo "curl output: $curl_output"  # For debugging (optional)

      - name: Create HTML file with timestamp
        run: |
          now=$(date +'%Y-%m-%d')  # Generate date only (without time)
          echo "$curl_output" > "webpage_$now.html"

      - name: Upload webpage as artifact
        uses: actions/upload-artifact@v3
        with:
          name: webpages
          path: 'webpage_*.html'

# Remove the commented-out push step if you don't need to push changes
# - name: (Optional) Push changes (requires push permission)
#   uses: actions/checkout@v3  # Use checkout for push (not needed for saving artifacts)
#   with:
#     github_token: ${{ secrets.GITHUB_TOKEN }}
#     branch: ${{ github.ref }}
#     force: true  # Force push if needed (use with caution)
